# Setup
title:        fedecarne.github.io
tagline:      Fede Carnevale's github page
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Fede Carnevale
  url:        https://fedecarne.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
