# Setup
title:        fede carnevale
tagline:      "I am a post-doctoral fellow at CSHL. I do neuroscience and machine learning."
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Fede Carnevale
  url:        https://fedecarne.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
